"""Pack/verify the Blender RGBA output. Run after block_fighter.py --render."""
from pathlib import Path
import hashlib
import argparse
import json
import math
from PIL import Image, ImageChops

HERE = Path(__file__).resolve().parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', nargs='?', type=Path, default=HERE/'generated')
SOURCE = parser.parse_args().source
OUT = HERE.parent / 'www/assets/blocks'
CELL, COLUMNS, GAME_HEIGHT = 224, 8, 90
EXPECTED = {'idle','crouch','walk','walkback','jump','fall','hitstun','blockstun','blockstun_low','jab','follow','heavy','low_light','low_medium','low_heavy','target','special','charged','finisher','multi','reload'}
m = json.loads((SOURCE/'manifest.json').read_text())
assert set(m['clips']) == EXPECTED, 'Missing or unexpected animation'
base = Image.open(SOURCE/'idle-001.png').convert('RGBA')
base_bounds = base.getchannel('A').getbbox()
ratio = CELL / base.width
scale = GAME_HEIGHT / ((base_bounds[3]-base_bounds[1])*ratio)
art = {'cell':CELL,'columns':COLUMNS,'scale':scale,'pivot':[m['pivot'][0]*ratio,base_bounds[3]*ratio],
       'walk_stride':48,'clips':{}}
OUT.mkdir(parents=True,exist_ok=True)
count = 0
for name,c in m['clips'].items():
    paths = sorted(SOURCE.glob(name+'-*.png'))
    assert len(paths) == c['count'], (name,len(paths),c['count'])
    sheet = Image.new('RGBA',(COLUMNS*CELL,math.ceil(c['count']/COLUMNS)*CELL))
    cells = []
    for i,p in enumerate(paths):
        im = Image.open(p)
        assert im.mode == 'RGBA' and im.size == (448,448), p
        a = im.getchannel('A'); bounds = a.getbbox()
        assert a.getextrema() == (0,255) and bounds and min(bounds[:2]) > 3 and max(bounds[2:]) < 445, (p,bounds)
        im = im.resize((CELL,CELL),Image.Resampling.LANCZOS)
        sheet.paste(im,((i%COLUMNS)*CELL,(i//COLUMNS)*CELL))
        cells.append(im)
        count += 1
    output = OUT/f'{name}.png'
    sheet.save(output,optimize=True)
    # Read every declared cell back; checking file dimensions alone misses atlas indexing bugs.
    with Image.open(output) as packed:
        for i,im in enumerate(cells):
            x,y=(i%COLUMNS)*CELL,(i//COLUMNS)*CELL
            assert packed.crop((x,y,x+CELL,y+CELL)).tobytes() == im.tobytes(), (name,i)
    if name not in {'jump','fall','hitstun','blockstun','blockstun_low','target'}:
        diff = ImageChops.difference(cells[0],cells[-1])
        assert diff.getchannel('A').getbbox() is None, name
        # Unassociated RGB at tiny alpha amplifies 1-bit render/resample rounding.
        # Judge visible RGB on both opaque backgrounds; keep alpha exact.
        for bg in ('black','white'):
            backing = Image.new('RGBA',cells[0].size,bg)
            visible = ImageChops.difference(Image.alpha_composite(backing,cells[0]),Image.alpha_composite(backing,cells[-1]))
            assert max(hi for lo,hi in visible.getextrema()) <= 1, name
    art['clips'][name] = {'frames':len(cells),'contacts':[[a-1,b-1] for a,b in c['contacts']],
        'impact_bounds':[[round((b[0]-m['pivot'][0])*ratio*scale,3),round((b[1]-base_bounds[3])*ratio*scale,3),
                          round((b[2]-m['pivot'][0])*ratio*scale,3),round((b[3]-base_bounds[3])*ratio*scale,3)] for b in c['impact_bounds']]}
assert count == sum(c['count'] for c in m['clips'].values())
entry = ImageChops.difference(Image.open(SOURCE/'target-001.png'),Image.open(SOURCE/'follow-013.png'))
entry_error = max(hi for lo,hi in entry.getextrema())
assert entry_error <= 2, ('Target entry no longer matches the hook',entry_error)
art['clips']['target']['entry_from'] = {'clip':'follow','frame':12}
# Static presentation metadata, not a second combat source or runtime character JSON fetch.
(OUT/'clips.js').write_text('// Generated by demo-wasm/art/pack_sprites.py\nexport default '+json.dumps(art,separators=(',',':'))+';\n',encoding='utf-8')
report = {'clips':len(art['clips']),'frames':count,'target_entry_rgba_error':entry_error,'atlas_roundtrip':'PASS_EVERY_CELL','transparent_bounds':'PASS_EVERY_FRAME',
          'source_sha256':hashlib.sha256((HERE/'block_fighter.py').read_bytes()).hexdigest(),
          'blend_sha256':hashlib.sha256((SOURCE/'block-fighter.blend').read_bytes()).hexdigest(),
          'atlas_bytes':sum(p.stat().st_size for p in OUT.glob('*.png')),'human_motion_verdict':'PENDING'}
(SOURCE/'pack-verification.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print(json.dumps(report,indent=2))
